USE [master]
GO

/****** Object:  Database [TradingApplication]    Script Date: 7/21/2025 11:13:15 PM ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'TradingApplication')
	BEGIN
		CREATE DATABASE [TradingApplication]
		 CONTAINMENT = NONE
		 ON  PRIMARY 
		( NAME = N'TradingApplication', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.APPDB\MSSQL\DATA\TradingApplication.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
		 LOG ON 
		( NAME = N'TradingApplication_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.APPDB\MSSQL\DATA\TradingApplication_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
		 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
	END
ELSE
    BEGIN
        PRINT 'Database [TradingApplication] already exists.';
    END

GO


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TradingApplication].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TradingApplication] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TradingApplication] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TradingApplication] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TradingApplication] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TradingApplication] SET ARITHABORT OFF 
GO

ALTER DATABASE [TradingApplication] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TradingApplication] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TradingApplication] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TradingApplication] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TradingApplication] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TradingApplication] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TradingApplication] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TradingApplication] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TradingApplication] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TradingApplication] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TradingApplication] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TradingApplication] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TradingApplication] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TradingApplication] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TradingApplication] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TradingApplication] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TradingApplication] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TradingApplication] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TradingApplication] SET  MULTI_USER 
GO

ALTER DATABASE [TradingApplication] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TradingApplication] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TradingApplication] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TradingApplication] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TradingApplication] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TradingApplication] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TradingApplication] SET QUERY_STORE = ON
GO

ALTER DATABASE [TradingApplication] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TradingApplication] SET  READ_WRITE 
GO
